extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ["true", "false", "on", "off"]
    check-keys: false
  braces:
    max-spaces-inside: 1
  empty-lines:
    max: 1
