networks:
  ai:
    driver: bridge

services: 
  faster-whisper:
      image: lscr.io/linuxserver/faster-whisper:latest
      container_name: faster-whisper
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - WHISPER_MODEL=base
        - WHISPER_BEAM=1 #optional
        - WHISPER_LANG=es 
      volumes:
        - /home/tofu/docker/whisper/data:/config
      ports:
        - 10300:10300
      restart: unless-stopped
      networks:
        - ai

  piper:
    image: lscr.io/linuxserver/piper:latest
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PIPER_VOICE=es_ES-sharvard-medium
      - PIPER_LENGTH=1.0 #optional
      - PIPER_NOISE=0.667 #optional
      - PIPER_NOISEW=0.333 #optional
      - PIPER_SPEAKER=0 #optional
      - PIPER_PROCS=1 #optional
    volumes:
      - /home/tofu/piper/data:/config
    ports:
      - 10200:10200
    restart: unless-stopped
    networks:
      - ai