services:
  cloudflare:
    container_name: cloudflare
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    networks:
      - homelab
      - mediaserver
      - portainer_bridge
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN

  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: favonia/cloudflare-ddns:latest
    network_mode: host
    restart: always
    user: "1000:1000"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    environment:
      - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      - DOMAINS=vpn.tofusito.org
      - PROXIED=false
      - IP6_PROVIDER=none

  twingate_connector:
    container_name: twingate_connector
    restart: unless-stopped
    image: "twingate/connector:latest"
    environment:
      - TWINGATE_NETWORK=$TWINGATE_NETWORK
      - TWINGATE_ACCESS_TOKEN=$TWINGATE_ACCESS_TOKEN
      - TWINGATE_REFRESH_TOKEN=$TWINGATE_REFRESH_TOKEN
    networks:
      - homelab



  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/tofu/docker/homarr/configs:/app/data/configs
      - /home/tofu/docker/homarr/icons:/app/public/icons
      - /home/tofu/docker/homarr/data:/data
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    ports:
      - '7575:7575'
    networks:
      - homelab
      - mediaserver
      - portainer_bridge

  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - 3001:3001
    volumes:
      - /:/mnt/host:ro
    networks:
      - homelab
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_CPU_TEMPS_MODE: 'avg'
      DASHDOT_WIDGET_LIST: 'ram,cpu,storage,network'  
      
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/tofu/docker/uk/data:/app/data
    ports:
      - 3002:3001
    restart: unless-stopped
    networks:
      - homelab
      - mediaserver

  wireguard:
    environment:
      - WG_HOST=vpn.tofusito.org
      - PASSWORD_HASH=$WG_PASSWORD
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    volumes:
      - /home/tofu/docker/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    networks:
      - homelab
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1



networks:
  homelab:
    driver: bridge
    name: homelab
  portainer_bridge:
    external: true
  mediaserver:
    external: true