services:

  forgejo:
    container_name: forgejo
    image: codeberg.org/forgejo/forgejo:14-rootless
    pull_policy: always
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - FORGEJO__server__DOMAIN=${FORGEJO_DOMAIN}
      - FORGEJO__server__ROOT_URL=https://${FORGEJO_DOMAIN}
      - FORGEJO__server__SSH_DOMAIN=${FORGEJO_DOMAIN}
      - FORGEJO__server__SSH_PORT=222
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__REQUIRE_SIGNIN_VIEW=true
    volumes:
      - forgejo-data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3002:3000"
      - "222:2222"
    networks:
      - forgejo
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cloudflare:
    container_name: cloudflare-forgejo
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      forgejo:
        condition: service_healthy
    networks:
      - forgejo

volumes:
  forgejo-data:
    name: forgejo-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/evo/git

networks:
  forgejo:
    driver: bridge
    name: forgejo
